/*
 * This source file was generated by the Gradle 'init' task
 */
package javalabravko3;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.print.DocFlavor.STRING;

public class App {
    
  

    public static void main(String[] args) {
       
        //tehtävä 1
        List<String> Teht1 = new ArrayList<String>();
        Teht1.add("omena");
        Teht1.forEach(System.out::println);
        
        //tehtävä2
        List<Integer> teht2 = new ArrayList <Integer>();
        teht2.add(10);
        teht2.add(20);
        System.out.println(teht2);

        //tehtävä 3
        List<String> animals = new ArrayList<String>();
        animals.add("kissa");
        animals.add("Koira");
        System.out.println(animals.getFirst());

        //tehtävä 4
        List<String> teht4 = new ArrayList<String>();
        teht4.add("A");
        teht4.add("B");
        teht4.add("C");
        teht4.remove("B");
        System.out.println(teht4);

        //tehtävä 5
        List <String> teht5 = new ArrayList<String>();
        teht5.add("yksi");
        teht5.add("kaksi");
        teht5.add("kolme");
        System.out.println(teht5.size());

        //tehtävä 6
        List <Integer> teht6 = new ArrayList<Integer>();
        teht6.add(1);
        teht6.add(2);
        teht6.add(3);
        for(Integer i : teht6){
            System.out.println(i);
        }
        
        
    }
}
